# Generated by Django 5.1.1 on 2024-10-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_purchasehistory_is_deleted_userprofile_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
