# Generated by Django 5.1.1 on 2024-10-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0004_customuser_is_deleted"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
