# Generated by Django 5.1.1 on 2025-01-21 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0008_alter_purchasehistory_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasehistory",
            name="address",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_history",
                to="user_management.address",
            ),
        ),
    ]
