# Generated by Django 5.1.1 on 2025-01-24 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_favoritelist_options_and_more"),
        ("user_management", "0009_alter_purchasehistory_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchasehistory",
            options={"ordering": ["-purchase_date"]},
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="is_delivered",
            field=models.BooleanField(
                default=False, help_text="Whether the product is delivered."
            ),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="address",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Address where the product will be delivered.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_history",
                to="user_management.address",
            ),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="The number of products purchased."
            ),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
