# Generated by Django 5.1.1 on 2025-03-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0012_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="fixed_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
