# Generated by Django 5.1.1 on 2025-05-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0013_customuser_fixed_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["city", "street"],
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["username"],
                "verbose_name": "Custom User",
                "verbose_name_plural": "Custom Users",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(
                help_text="Age must be at least 13 years old.", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="unique_default_address_per_user",
            ),
        ),
    ]
