# Generated by Django 5.1.1 on 2025-05-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_management",
            "0014_alter_address_options_alter_customuser_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
