# Generated by Django 5.1.1 on 2024-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_cart_updated_at_cartproduct_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="favoritelist",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rating",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
