# Generated by Django 5.1.1 on 2025-01-21 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_brand_product_brand"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="dislike",
            field=models.ManyToManyField(
                blank=True, related_name="disliked_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="liked_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="parent_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="product.review",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rate",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
