# Generated by Django 5.1.1 on 2025-01-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_review_dislike_review_like_review_parent_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.PositiveIntegerField(
                choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=0,
            ),
        ),
    ]
