# Generated by Django 5.1.1 on 2025-01-24 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_rating_status_alter_rating_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="discount",
            new_name="discount_value",
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="min_purchase",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="used_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
