# Generated by Django 5.1.1 on 2025-01-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_rename_discount_coupon_discount_value_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favoritelist",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="favoritelist",
            name="product_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
