# Generated by Django 5.1.1 on 2025-03-27 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0015_brand_popularity_question_is_approved_question_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="warranty",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.warranty",
            ),
        ),
    ]
