# Generated by Django 5.1.1 on 2025-03-27 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_alter_product_warranty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="warranty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.warranty",
            ),
        ),
    ]
