# Generated by Django 5.1.1 on 2025-03-30 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_alter_product_warranty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warranty",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
