# Generated by Django 5.1.1 on 2025-03-30 11:27

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_alter_warranty_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warranty",
            name="end_date",
            field=models.DateField(default=product.models.default_end_date),
        ),
    ]
