# Generated by Django 5.1.1 on 2024-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_aboutus_created_at_aboutus_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactus",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="faq",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
