# Generated by Django 5.1.1 on 2025-01-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_aboutus_is_deleted_contactus_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="title",
            field=models.CharField(default="Default Title", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactus",
            name="map_location",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactus",
            name="social_media_links",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactus",
            name="working_hours",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
