# Generated by Django 5.1.1 on 2025-05-18 11:45

import django.db.models.deletion
import info.validation
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0005_privacypolicy_teammember_termsandconditions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="phone",
            field=models.CharField(
                help_text="Enter only the last 8 digits of the company number (without 021)",
                max_length=20,
                validators=[info.validation.validate_company_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="social_media_links",
            field=models.JSONField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="locationmap",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location_maps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="version",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[info.validation.validate_version_format],
            ),
        ),
        migrations.AlterField(
            model_name="sitestat",
            name="stat_value",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="sitestat",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_state_update",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Enter only the last 8 digits of the number (without 021)",
                max_length=20,
                null=True,
                validators=[info.validation.validate_company_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="termsandconditions",
            name="version",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[info.validation.validate_version_format],
            ),
        ),
        migrations.AddConstraint(
            model_name="faq",
            constraint=models.UniqueConstraint(
                fields=("question",), name="unique_faq_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="locationmap",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude"), name="unique_location_coords"
            ),
        ),
        migrations.AddConstraint(
            model_name="privacypolicy",
            constraint=models.UniqueConstraint(
                fields=("title", "version"), name="unique_policy_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="sitestat",
            constraint=models.UniqueConstraint(
                fields=("stat_name",), name="unique_stat_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("name", "role"), name="unique_team_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="termsandconditions",
            constraint=models.UniqueConstraint(
                fields=("title", "version"), name="unique_terms_version"
            ),
        ),
    ]
