# Generated by Django 5.1.1 on 2025-01-30 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0005_remove_order_products_alter_order_status"),
        ("user_management", "0012_alter_userprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estimated_days", models.PositiveIntegerField()),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("shipped_date", models.DateTimeField(blank=True, null=True)),
                ("delivered_date", models.DateTimeField(blank=True, null=True)),
                ("is_delivered", models.BooleanField(default=False)),
                (
                    "estimated_delivery_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.address",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="order.order",
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipping.shippingmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["-shipped_date"],
            },
        ),
    ]
