# Generated by Django 5.1.1 on 2025-03-31 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_order_payment_status_order_shipping_date_and_more"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipment",
                to="order.order",
            ),
        ),
    ]
