# Generated by Django 5.2.6 on 2025-10-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_alter_shipment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
