# Generated by Django 5.1.1 on 2025-01-21 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_products_order_total_amount_alter_order_status"),
        ("user_management", "0007_remove_userprofile_address_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="user_management.address",
            ),
        ),
    ]
