# Generated by Django 5.1.1 on 2025-01-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_address"),
        ("user_management", "0009_alter_purchasehistory_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="user_management.address",
            ),
        ),
    ]
