# Generated by Django 5.1.1 on 2025-05-20 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_order_payment_status_order_shipping_date_and_more"),
        ("user_management", "0013_customuser_fixed_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, help_text="Order Notes", null=True),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("user", "tracking_number"), name="unique_user_tracking"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("transaction_id",), name="unique_transaction_id"
            ),
        ),
    ]
